{% set name = "cvat-sdk" %}
{% set version = "2.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cvat_sdk-{{ version }}.tar.gz
  sha256: ea0dd46a5fa30032296d642318a9abf25a71d27c40cb9fd7fdd59c1cb4c9ea6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=21.4.0
    - packaging >=21.3
    - pillow >=10.3.0
    - platformdirs >=2.1.0
    - tqdm >=4.64.0
    - tuspy ==0.2.5
    - typing_extensions >=4.2.0
    - python-dateutil >=2.5.3
    - urllib3 >=1.25.3

test:
  imports:
    - cvat_sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: cvat-sdk
  - name: cvat-sdk-masks
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - wheel
        - pip
      run:
        - python >={{ python_min }}
        - python-dateutil >=2.5.3
        - {{ pin_subpackage('cvat-sdk', exact=True) }}
        - numpy >=2
    test:
      imports:
        - cvat_sdk
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}
    build:
      noarch: python
  - name: cvat-sdk-pytorch
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - wheel
        - pip
      run:
        - python >={{ python_min }}
        - python-dateutil >=2.5.3
        - {{ pin_subpackage('cvat-sdk', exact=True) }}
        - pytorch
        - torchvision
        - scikit-image >=0.24
    test:
      imports:
        - cvat_sdk
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}
    build:
      noarch: python

about:
  home: https://www.cvat.ai/
  summary: CVAT REST API
  doc_url: https://docs.cvat.ai/docs/api_sdk/sdk
  dev_url: https://github.com/cvat-ai/cvat
  license: MIT
  license_file: LICENSE

extra:
  feedstock-name: cvat-sdk
  recipe-maintainers:
    - achimgaedke
