schema_version: 1

context:
  name: cvat-sdk
  version: "2.48.1"

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cvat_sdk-${{ version }}.tar.gz
  sha256: 111fa16c6ca1228825e64ebc5f76b4a8d504d47335f6e11d3a934574e3f6802b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


outputs:
  - package:
      name: cvat-sdk
    requirements:
      host:
        - python ${{ python_min }}.*
        - setuptools >=21.0.0
        - wheel
        - pip
      run:
        - python >=${{ python_min }}
        - attrs >=21.4.0
        - packaging >=21.3
        - pillow >=10.3.0
        - platformdirs >=2.1.0
        - tqdm >=4.64.0
        - tuspy ==0.2.5
        - typing_extensions >=4.2.0
        - python-dateutil >=2.5.3
        - urllib3 >=1.25.3
        - setuptools >=21.0.0
    tests:
      - python:
          imports:
            - cvat_sdk
      - requirements:
          run:
            - pip
            - python ${{ python_min }}
        script:
          - pip check
  - package:
      name: cvat-sdk-masks
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
        - setuptools >=21.0.0
        - wheel
        - pip
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('cvat-sdk', exact=True) }}
        - numpy >=2
    tests:
      - python:
          imports:
            - cvat_sdk
      - requirements:
          run:
            - pip
            - python ${{ python_min }}
        script:
          - pip check
  - package:
      name: cvat-sdk-pytorch
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
        - setuptools >=21.0.0
        - wheel
        - pip
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('cvat-sdk-masks', exact=True) }}
        - pytorch
        - torchvision
        - scikit-image >=0.24
    tests:
      - python:
          imports:
            - cvat_sdk
      - requirements:
          run:
            - pip
            - python ${{ python_min }}
        script:
          - pip check

about:
  summary: CVAT REST API
  license: MIT
  license_file: LICENSE
  homepage: https://www.cvat.ai/
  repository: https://github.com/cvat-ai/cvat
  documentation: https://docs.cvat.ai/docs/api_sdk/sdk

extra:
  feedstock-name: cvat-sdk
  recipe-maintainers:
    - achimgaedke
